# permissions for end users to view kustomizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kustomization-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: flux-api-conversionwebhook
    app.kubernetes.io/part-of: flux-api-conversionwebhook
    app.kubernetes.io/managed-by: kustomize
  name: kustomization-viewer-role
rules:
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations/status
  verbs:
  - get
