# permissions for end users to edit receivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: receiver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: flux-api-conversionwebhook
    app.kubernetes.io/part-of: flux-api-conversionwebhook
    app.kubernetes.io/managed-by: kustomize
  name: receiver-editor-role
rules:
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - receivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.toolkit.fluxcd.io
  resources:
  - receivers/status
  verbs:
  - get
