apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Receiver
metadata:
  labels:
    app.kubernetes.io/name: receiver
    app.kubernetes.io/instance: receiver-sample
    app.kubernetes.io/part-of: flux-api-conversionwebhook
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: flux-api-conversionwebhook
  name: receiver-sample
spec:
  # TODO(user): Add fields here
